name: 02 - Workflow Events

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: |
          echo "Event NAme: ${{ github.event_name }}"
