name: Context Workflow

on:
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    
    steps:
      uses: actions/checkout@v4

    - name: Environment Setup
      run: | 
        if["${{github.ref_name}}"=="main]; then
          echo "ENVIRONMENT=Production" >> $GITHUB_ENV
          echo "API_URL=https://api.example.com" >> $GITHUB_ENV
          echo "MESSAGE=Deploying to production" >> $GITHUB_ENV
        elif["${{github.ref_name}}"=="develop"]; then
          echo "ENVIRONMENT=Staging">>$GITHUB_ENV
          echo "API_URL=https://staging-api.example.com" >> $GITHUB_ENV
          echo "MESSAGE=deploying to stage" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Deployment info
      run: | 
        echo "Environment: $ENVIRONMENT"
        echo "API URL: $API_URL
          
