name: Pull request with specific type

on:
  pull_request:
    types:
      - opened
      # - reopened

jobs:
  echo-ubuntu-py:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "Hello, World!"
