name: Node-Application

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Setup NodeJS 
        uses: actions/setup-node@v4
        with: 
          node-version: '20.18.1'

      - name: Install Dependencies
        run: npm install
