name: On Push With Branch Pattern

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: linux
        run: | 
          echo "Running on linux"
          echo "Runner OS is $RUNNER_OS"
